#ifndef TIME_CONSTANTS_H
#define TIME_CONSTANTS_H

#define CP_NANOS_IN_ONE  1000000000ll
#define CP_MICROS_IN_ONE 1000000ll
#define CP_MILLIS_IN_ONE 1000ll

#define CP_MICROS_IN_NANO (long long)(CP_NANOS_IN_ONE / CP_MICROS_IN_ONE)
#define CP_MILLIS_IN_NANO (long long)(CP_NANOS_IN_ONE / CP_MILLIS_IN_ONE)

#endif // TIME_CONSTANTS_H
